# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

Generate matricies

In [26]:
def fill_mat(x,y):
    
    import numpy as np
    import random
    
    mat = np.zeros((x,y))
    
    for x in range(0, mat.shape[0]):
        for y in range(0, mat.shape[1]):
            mat[x][y] = np.random.randint(1,10)
            
    return mat

In [27]:
# Your code here
fill_mat(3,2)

array([[6., 3.],
       [4., 7.],
       [5., 5.]])

In [28]:
#Distributive property

In [29]:
A = fill_mat(3,3)
B = fill_mat(3,3)
C = fill_mat(3,3)

r = A.dot(B+C)
s = A.dot(B) + A.dot(C)

print(r)
print(s)

[[151. 124. 132.]
 [ 63.  92.  86.]
 [197. 197. 198.]]
[[151. 124. 132.]
 [ 63.  92.  86.]
 [197. 197. 198.]]


## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [31]:
# Your code here 

r = A.dot(B.dot(C))
s = A.dot(B).dot(C)

print(r)
print(s)

[[ 695. 1165. 1302.]
 [ 355.  525.  616.]
 [ 964. 1556. 1764.]]
[[ 695. 1165. 1302.]
 [ 355.  525.  616.]
 [ 964. 1556. 1764.]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [32]:
# Your code here 
r = A.dot(B)
s = B.dot(A)

print(r)
print(s)

[[ 97.  48.  41.]
 [ 31.  34.  23.]
 [119.  75.  58.]]
[[40. 22. 27.]
 [62. 58. 91.]
 [63. 59. 91.]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [33]:
# Your code here 

r = A.T.dot(B)
s = B.T.dot(A)

print(r)
print(s)

[[113.  54.  49.]
 [ 65.  42.  31.]
 [ 87.  63.  42.]]
[[113.  65.  87.]
 [ 54.  42.  63.]
 [ 49.  31.  42.]]


## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [34]:
# Your code here 

r = (A.dot(B)).T
s = B.T.dot(A.T)

print(r)
print(s)

[[ 97.  31. 119.]
 [ 48.  34.  75.]
 [ 41.  23.  58.]]
[[ 97.  31. 119.]
 [ 48.  34.  75.]
 [ 41.  23.  58.]]


## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 